// Pre-processes the world map once at build time so the browser only downloads
// a cached JSON file (no world-atlas or ISO lookup tables in the JS bundle).
//   - drops Antarctica, puts { name, iso3 } on every country
//   - writes public/geo/world-110m.<hash>.json (immutable-cached by next.config.ts)
//   - writes components/map/helpers/world-geo.ts with its URL and the map height
import { createHash } from "node:crypto"
import { mkdirSync, readdirSync, readFileSync, rmSync, writeFileSync } from "node:fs"
import { createRequire } from "node:module"
import path from "node:path"

import countries from "i18n-iso-countries"

import { buildGeometry, type WorldTopology } from "../components/map/helpers/geo.ts"

const require = createRequire(import.meta.url)
const root = path.resolve(import.meta.dirname, "..")
const world = JSON.parse(readFileSync(require.resolve("world-atlas/countries-110m.json"), "utf8"))

// world-atlas uses ISO 3166 numeric ids; a few disputed areas have none.
const NAME_OVERRIDES: Record<string, string> = { Kosovo: "XKX" }

const object = world.objects.countries
object.geometries = object.geometries
  .filter((g: { properties: { name: string } }) => g.properties.name !== "Antarctica")
  .map((g: { id?: string; properties: { name: string } }) => ({
    ...g,
    properties: {
      name: g.properties.name,
      iso3: NAME_OVERRIDES[g.properties.name] ?? (g.id ? (countries.numericToAlpha3(g.id) ?? null) : null),
    },
  }))

const json = JSON.stringify(world)
const hash = createHash("sha256").update(json).digest("hex").slice(0, 10)
const outDir = path.join(root, "public/geo")
mkdirSync(outDir, { recursive: true })
for (const file of readdirSync(outDir)) if (file.startsWith("world-110m.")) rmSync(path.join(outDir, file))
writeFileSync(path.join(outDir, `world-110m.${hash}.json`), json)

const { height } = buildGeometry(world as WorldTopology)
writeFileSync(
  path.join(root, "components/map/helpers/world-geo.ts"),
  `// Generated by scripts/build-geo.mts. Do not edit.\n` +
    `export const WORLD_GEO_URL = "/geo/world-110m.${hash}.json"\n` +
    `export const WORLD_MAP_HEIGHT = ${height}\n`
)
console.log(`geo: /geo/world-110m.${hash}.json (${(json.length / 1024).toFixed(0)} KiB, height ${height})`)
